#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Reusable video-to-learning-material pipeline for the CLI and Obsidian plugin."""

from __future__ import annotations

import os
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional

from processor import TaskStatus, process_video_task, tasks, tasks_lock


@dataclass
class PipelineJob:
    urls: List[str]
    output_dir: str = "subtitles"
    model_name: Optional[str] = None
    cookies_file: str = "cookies.txt"
    workspace_name: Optional[str] = None
    download_all_parts: bool = False
    max_parts: Optional[int] = None
    start_index: Optional[int] = None
    end_index: Optional[int] = None
    asr_model_size: str = "small"
    asr_device: str = "auto"
    asr_compute_type: str = "auto"
    max_workers: int = 1
    generate_options: Dict[str, bool] = field(default_factory=lambda: {
        "summary": True,
        "full_content": True,
        "exercises": False,
        "questions": False,
    })
    prompt_config: Dict[str, Any] = field(default_factory=dict)
    ffmpeg_path: Optional[str] = None


def _workspace_output_dir(output_dir: str, workspace_name: Optional[str]) -> str:
    output_dir = output_dir or "subtitles"
    if not workspace_name:
        return output_dir

    workspace_name = str(workspace_name).replace("\\", "/").strip().strip("/")
    normalized_workspace = os.path.normpath(workspace_name)
    if (
        not normalized_workspace
        or os.path.isabs(normalized_workspace)
        or normalized_workspace == ".."
        or normalized_workspace.startswith(f"..{os.sep}")
    ):
        return output_dir
    return os.path.join(output_dir, normalized_workspace)


def run_pipeline(job: PipelineJob) -> Dict[str, Any]:
    """Run the existing processing flow for all URLs and return task results."""
    if not job.urls:
        raise ValueError("At least one video URL is required.")

    effective_output_dir = _workspace_output_dir(job.output_dir, job.workspace_name)
    os.makedirs(effective_output_dir, exist_ok=True)

    def run_one(index: int, url: str) -> Dict[str, Any]:
        task_id = f"cli-{uuid.uuid4()}"
        with tasks_lock:
            tasks[task_id] = {
                "id": task_id,
                "url": url,
                "status": TaskStatus.PENDING,
                "message": "Queued from CLI",
                "stop_flag": False,
            }

        process_video_task(
            task_id=task_id,
            thread_name=f"CLI-{index}",
            url=url,
            output_dir=effective_output_dir,
            model_name=job.model_name,
            cookies_file=job.cookies_file,
            custom_folder_name=None,
            download_all_parts=job.download_all_parts,
            generate_options=job.generate_options,
            prompt_config=job.prompt_config,
            ffmpeg_path=job.ffmpeg_path,
            max_parts=job.max_parts,
            start_index=job.start_index,
            end_index=job.end_index,
            asr_model_size=job.asr_model_size,
            asr_device=job.asr_device,
            asr_compute_type=job.asr_compute_type,
        )

        with tasks_lock:
            result = dict(tasks.get(task_id, {}))
        return result

    max_workers = max(1, int(job.max_workers or 1))
    if max_workers == 1 or len(job.urls) == 1:
        results = [run_one(index, url) for index, url in enumerate(job.urls, 1)]
    else:
        results = [{} for _ in job.urls]
        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            future_map = {
                executor.submit(run_one, index, url): index - 1
                for index, url in enumerate(job.urls, 1)
            }
            for future in as_completed(future_map):
                results[future_map[future]] = future.result()

    success = all(item.get("status") == TaskStatus.COMPLETED for item in results)
    return {
        "success": success,
        "output_dir": os.path.abspath(effective_output_dir),
        "results": results,
    }


def iter_generated_markdown(results: Iterable[Dict[str, Any]]) -> Iterable[str]:
    """Yield Markdown files generated by process_video_task results."""
    for result in results:
        files = result.get("files") or {}
        for item in files.get("generated_files") or []:
            path = item.get("content_md")
            if path:
                yield path
